repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/autoflake
    rev: v1.6.1
    hooks:
      - id: autoflake
        args:
          [
            "--remove-all-unused-imports",
            "--expand-star-imports",
            "--ignore-init-module-imports",
          ]

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: ^notebooks/
        additional_dependencies:
          - flake8-eradicate

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      args:
        [
          "--line-length=100",
          "--skip-string-normalization",
          "--fast",
        ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0 # Use the sha / tag you want to point at

    hooks:
      - id: mypy
        files: '^conversational_commerce_sl/.*\.py'
        entry: mypy .
        pass_filenames: false
